services:
  web:
    build:
      context: ./betterbnb_backend # Specifies the directory containing the Dockerfile
      # dockerfile: Dockerfile # Optional: specify if your Dockerfile has a non-standard name
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # Mounts the host's ./betterbnb_backend directory to /usr/src/betterbnb_backend in the container
      # This should match the WORKDIR in your Dockerfile
      - ./betterbnb_backend/:/usr/src/betterbnb_backend/
    ports:
      - "8000:8000"
    env_file:
      - ./betterbnb_backend/.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: betterbnb
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
  
volumes:
  postgres_data:

