# Generated by Django 5.0.2 on 2025-05-30 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_reservations_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='property.property'),
        ),
    ]
